name: CI
on:
  push:

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: xbrowser-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: |
            xbrowser-yarn-
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # if: contains(github.ref, 'tags/release')
        run: |
          remote_url=`git remote get-url --push origin`
          cd dist
          git init
          git config --local github.token $GITHUB_TOKEN
          git config --local user.name $GITHUB_ACTOR
          git checkout -b release
          git remote add origin $remote_url
          git add .
          git commit -m "Release"
          git push
