name: CI
on:
  push:

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: xbrowser-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: |
            xbrowser-yarn-
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # if: contains(github.ref, 'tags/release')
        run: |
          remote_url=`git remote get-url --push origin`
          remote_url=https://$GITHUB_ACTOR:$GITHUB_TOKEN@${remote_url#*//}
          echo remote_url
          cp -r .git dist/
          cd dist
          # git config --global user.name $GITHUB_ACTOR
          # git config --global user.email ${GITHUB_ACTOR}@git 1
          git checkout --force -b release
          git remote set-url origin $remote_url
          git add index.js action.yml
          git commit -m "Release"
          git push origin release -f
