name: CI
on:
  push:

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: message test
        uses: SoraKumo001/github-action@master
        with:
          message: 'abcdefaaa'
